CREATE TABLE client (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL CHECK (LENGTH(Name) >= 3 AND LENGTH(Name) <= 200)
);

CREATE TABLE planet (
    ID VARCHAR(100) PRIMARY KEY CONSTRAINT caps CHECK (ID ~ '^[A-Z0-9]+$'),
    Name VARCHAR(500) NOT NULL CHECK (LENGTH(Name) >= 1 AND LENGTH(Name) <= 500)
);

CREATE TABLE ticket (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CLIENT_ID INT,
    FROM_PLANET_ID VARCHAR(100) CONSTRAINT caps1 CHECK (FROM_PLANET_ID ~ '^[A-Z0-9]+$'),
    TO_PLANET_ID VARCHAR(100) CONSTRAINT caps2 CHECK (TO_PLANET_ID ~ '^[A-Z0-9]+$'),
    FOREIGN KEY (CLIENT_ID) REFERENCES client(ID),
    FOREIGN KEY (FROM_PLANET_ID) REFERENCES planet(ID),
    FOREIGN KEY (TO_PLANET_ID) REFERENCES planet(ID)
);